/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RelativeLineNumbersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var RelativeLineNumbersPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Relative Line Numbers plugin");
    this.registerEditorExtension([
      relativeLineNumberGutter(),
      // Hide Obsidian's default line numbers
      import_view.EditorView.baseTheme({
        ".cm-lineNumbers": {
          display: "none !important"
        }
      })
    ]);
  }
  onunload() {
    console.log("Unloading Relative Line Numbers plugin");
  }
};
var RelativeLineNumberMarker = class extends import_view.GutterMarker {
  constructor(number, isCurrent) {
    super();
    this.number = number;
    this.isCurrent = isCurrent;
  }
  toDOM() {
    const div = document.createElement("div");
    div.className = "cm-relative-lineNumber" + (this.isCurrent ? " current" : "");
    div.textContent = String(this.number);
    return div;
  }
};
function relativeLineNumberGutter() {
  return [
    (0, import_view.gutter)({
      class: "cm-relative-gutter",
      markers: (view) => relativeLineNumberMarkers(view),
      initialSpacer: () => new RelativeLineNumberMarker(99999, false)
    }),
    // Custom styling for the gutter
    import_view.EditorView.baseTheme({
      ".cm-relative-gutter": {
        backgroundColor: "var(--background-primary)",
        borderRight: "1px solid var(--background-modifier-border)",
        minWidth: "3.5ch",
        paddingRight: "8px"
      },
      ".cm-relative-gutter .cm-gutterElement": {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        minHeight: "var(--line-height-normal)",
        padding: "0"
      },
      ".cm-relative-lineNumber": {
        color: "var(--text-faint)",
        fontFamily: "var(--font-monospace)",
        fontSize: "1.2em",
        textAlign: "right",
        userSelect: "none",
        width: "100%"
      },
      ".cm-relative-lineNumber.current": {
        color: "var(--text-normal)",
        fontWeight: "bold"
      }
    }),
    // Update on selection changes
    import_view.ViewPlugin.fromClass(class {
      constructor(view) {
        this.view = view;
      }
      update(update) {
        if (update.selectionSet || update.viewportChanged) {
          update.view.requestMeasure();
        }
      }
    })
  ];
}
function relativeLineNumberMarkers(view) {
  const builder = new import_state.RangeSetBuilder();
  const cursorLine = view.state.doc.lineAt(view.state.selection.main.head).number;
  for (let { from, to } of view.visibleRanges) {
    for (let pos = from; pos <= to; ) {
      const line = view.state.doc.lineAt(pos);
      const lineNumber = line.number;
      const displayNumber = lineNumber === cursorLine ? lineNumber : Math.abs(lineNumber - cursorLine);
      builder.add(
        line.from,
        line.from,
        new RelativeLineNumberMarker(displayNumber, lineNumber === cursorLine)
      );
      pos = line.to + 1;
    }
  }
  return builder.finish();
}
